export const BOOK_CATEGORIES = [
  { id: 'all', label: 'Tümü', icon: '📚' },
  { id: 'roman', label: 'Roman', icon: '📖' },
  { id: 'bilim', label: 'Bilim', icon: '🔬' },
  { id: 'tarih', label: 'Tarih', icon: '🏛️' },
  { id: 'felsefe', label: 'Felsefe', icon: '🧠' },
  { id: 'psikoloji', label: 'Psikoloji', icon: '🧬' },
  { id: 'kisisel-gelisim', label: 'Kişisel Gelişim', icon: '🚀' },
  { id: 'bilim-kurgu', label: 'Bilim Kurgu', icon: '🛸' },
  { id: 'fantastik', label: 'Fantastik', icon: '🧙' },
  { id: 'biyografi', label: 'Biyografi', icon: '👤' },
  { id: 'din', label: 'Din & Maneviyat', icon: '☪️' },
  { id: 'siir', label: 'Şiir', icon: '✍️' },
  { id: 'cocuk', label: 'Çocuk Kitapları', icon: '🧒' },
  { id: 'ekonomi', label: 'Ekonomi', icon: '💰' },
  { id: 'siyaset', label: 'Siyaset', icon: '🏛' },
  { id: 'sanat', label: 'Sanat & Tasarım', icon: '🎨' },
  { id: 'yazilim', label: 'Yazılım', icon: '💻' },
  { id: 'saglik', label: 'Sağlık', icon: '💊' },
  { id: 'korku', label: 'Korku', icon: '👻' },
  { id: 'romantik', label: 'Romantik', icon: '❤️' },
  { id: 'gezi', label: 'Gezi & Keşif', icon: '🌍' },
  { id: 'mizah', label: 'Mizah', icon: '😄' },
  { id: 'alinti', label: 'Sadece Alıntı', icon: '💬' },
]
